version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TestDocumentApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q52gionhjeg3"
s3_prefix = "TestDocumentApi"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ContextId=\"694\" ClientId=\"ThetisClientId\" ClientSecret=\"ThetisClientSecret\" WebAcl=\"ThetisWebAcl\" ApiKey=\"2f38b13d-4246-40fc-9118-dd271dd2e33e\" DevOpsEmail=\"lmp@thetis-apps.com\""
image_repositories = []
resolve_s3 = true
